# Generated by Django 2.0.2 on 2018-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='sales/%Y-%m-%d')),
                ('title', models.CharField(max_length=140)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_uploaded', models.DateField(auto_now=True)),
            ],
        ),
    ]
