# Generated by Django 2.0.2 on 2018-02-23 05:35

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sorl.thumbnail.fields.ImageField(null=True, upload_to='shop-items/')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, default='Untitled', max_length=180),
        ),
        migrations.AddField(
            model_name='item',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='+', to='shop.Photo'),
        ),
        migrations.AddField(
            model_name='item',
            name='photos',
            field=models.ManyToManyField(related_name='_item_photos_+', to='shop.Photo'),
        ),
    ]
