# Generated by Django 2.0.2 on 2018-02-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180223_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=180)),
                ('items', models.ManyToManyField(related_name='_cart_items_+', to='shop.Item')),
            ],
        ),
    ]
