# Generated by Django 2.0.2 on 2018-02-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180215_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(related_name='project', to='projects.Photo'),
        ),
    ]
